title: NP-complete in a polynomial world
# email:
description: >-
  Little thoughts about hardware synthesis and verification for your amusement.
baseurl: ""
url: "georgerennie.github.io"
github_username: georgerennie

# Build settings
theme: minima
plugins:
  - jekyll-feed

show_excepts: true
