title: soup thoughts
# email:
description: >-
  little thoughts about hardware synthesis and verification for your amusement
baseurl: "/blog"
url: "georgerennie.github.io"
github_username: georgerennie

# Build settings
theme: minima
plugins:
  - jekyll-feed

show_excepts: true
